[project]
name = "leetcode"
version = "0.1.0"
description = "Add a short description here"
authors = ["notPlancha <andre.plancha@hotmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]
# profile = "python -m pyinstrument -o temp.txt"
profile-line = "kernprof -lv"
profile-c = "python -m cProfile"
# profile-graph = "pycallgraph graphviz --"
# profile-viz = "snakeviz temp.prof"

[dependencies]
python = "==3.11"
sortedcontainers = ">=2.4.0,<2.5"
icecream = ">=2.1.3,<2.2"
snakeviz = ">=2.2.0,<2.3"
more-itertools = ">=10.2.0,<10.3"
# pyinstrument = ">=4.6.2,<4.7"
# line_profiler = ">=4.1.1,<4.2"
# pyprof2calltree = ">=1.4.5,<1.5"
# pycallgraph2 = ">=1.1.3,<1.2"
# graphviz = ">=9.0.0,<9.1"

[pypi-dependencies]
watchpoints = "*"
line-profiler-pycharm = "*"
pytictoc = "*"
