[project]
name = "leetcode"
version = "0.1.0"
description = "Add a short description here"
authors = ["notPlancha <andre.plancha@hotmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]
# profile = "python -m pyinstrument"
profile = "kernprof -lv"
profile-c = "python -m cProfile"
# profile-viz = "snakeviz temp.prof"

[dependencies]
python = "==3.11"
icecream = ">=2.1.3,<2.2"
snakeviz = ">=2.2.0,<2.3"
pyinstrument = ">=4.6.2,<4.7"
line_profiler = ">=4.1.1,<4.2"

[pypi-dependencies]
watchpoints = "*"
line-profiler-pycharm = "*"
