[project]
name = "leetcode"
version = "0.1.0"
description = "Add a short description here"
authors = ["notPlancha <andre.plancha@hotmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]
profile = "python -m cProfile -o temp.prof"
profile-viz = "snakeviz temp.prof"

[dependencies]
python = "==3.11"
icecream = ">=2.1.3,<2.2"
snakeviz = ">=2.2.0,<2.3"

[pypi-dependencies]
watchpoints = "*"
